export interface IServicePriceList {
  [serviceType: string]: {
    [claveDeServicio: string]: {
      nombre: string;
      precio: number;
    };
  };
}

//Rnagos por M2
export const RANGO_M2_MAP = {
  '0-300': 'A',
  '301-600': 'B',
  '601-5000': 'C',
};

//función para ubicar Rango por M2
export function getRangoM2Key(cantidadM2: number): string {
  if (cantidadM2 >= 0 && cantidadM2 <= 300) return RANGO_M2_MAP['0-300'];
  if (cantidadM2 >= 301 && cantidadM2 <= 600) return RANGO_M2_MAP['301-600'];
  if (cantidadM2 >= 601 && cantidadM2 <= 5000) return RANGO_M2_MAP['601-5000'];
  // agregar else despues... 
  return 'X'; // mientas culaquier identificador de error
}

//LISTA DE PRECIOS
export const ServiciosPrecios: IServicePriceList = {
  PINTURA: {
    // --- STAR COLORS VIN R (Original: EXTERIOR PRO) ---
    'PEALSCVINRM2': { nombre: "Servicio de aplicación de pintura vinílica Star Colors Vinilica R para exterior en superficie con acabado liso", precio: 49 },
    'PEBLSCVINRM2': { nombre: "Servicio de aplicación de pintura vinílica Star Colors Vinilica R para exterior en superficie con acabado liso", precio: 47 },
    'PECLSCVINRM2': { nombre: "Servicio de aplicación de pintura vinílica Star Colors Vinilica R para exterior en superficie con acabado liso", precio: 45 },
    'PEARSCVINRM2': { nombre: "Servicio de aplicación de pintura vinílica Star Colors Vinilica R para exterior en superficie con acabado rugoso", precio: 57 },
    'PEBRSCVINRM2': { nombre: "Servicio de aplicación de pintura vinílica Star Colors Vinilica R para exterior en superficie con acabado rugoso", precio: 54 },
    'PECRSCVINRM2': { nombre: "Servicio de aplicación de pintura vinílica Star Colors Vinilica R para exterior en superficie con acabado rugoso", precio: 51 },
    'PEAXSCVINRM2': { nombre: "Servicio de aplicación de pintura vinílica Star Colors Vinilica R para exterior en superficie con acabado extra rugoso", precio: 74 },
    'PEBXSCVINRM2': { nombre: "Servicio de aplicación de pintura vinílica Star Colors Vinilica R para exterior en superficie con acabado extra rugoso", precio: 71 },
    'PECXSCVINRM2': { nombre: "Servicio de aplicación de pintura vinílica Star Colors Vinilica R para exterior en superficie con acabado extra rugoso", precio: 67 },
    'PIALSCVINRM2': { nombre: "Servicio de aplicación de pintura vinílica Star Colors Vinilica R para interior en superficie con acabado liso", precio: 49 },
    'PIBLSCVINRM2': { nombre: "Servicio de aplicación de pintura vinílica Star Colors Vinilica R para interior en superficie con acabado liso", precio: 47 },
    'PICLSCVINRM2': { nombre: "Servicio de aplicación de pintura vinílica Star Colors Vinilica R para interior en superficie con acabado liso", precio: 45 },
    'PIARSCVINRM2': { nombre: "Servicio de aplicación de pintura vinílica Star Colors Vinilica R para interior en superficie con acabado rugoso", precio: 57 },
    'PIBRSCVINRM2': { nombre: "Servicio de aplicación de pintura vinílica Star Colors Vinilica R para interior en superficie con acabado rugoso", precio: 54 },
    'PICRSCVINRM2': { nombre: "Servicio de aplicación de pintura vinílica Star Colors Vinilica R para interior en superficie con acabado rugoso", precio: 51 },
    'PIAXSCVINRM2': { nombre: "Servicio de aplicación de pintura vinílica Star Colors Vinilica R para interior en superficie con acabado extra rugoso", precio: 74 },
    'PIBXSCVINRM2': { nombre: "Servicio de aplicación de pintura vinílica Star Colors Vinilica R para interior en superficie con acabado extra rugoso", precio: 71 },
    'PICXSCVINRM2': { nombre: "Servicio de aplicación de pintura vinílica Star Colors Vinilica R para interior en superficie con acabado extra rugoso", precio: 67 },

    // --- STAR COLORS VIN E (Original: PREMIUM MATE) ---
    'PEALSCVINEM2': { nombre: "Servicio de aplicación de pintura vinílica Star Colors Vinilica E para exterior en superficie con acabado liso", precio: 52 },
    'PEBLSCVINEM2': { nombre: "Servicio de aplicación de pintura vinílica Star Colors Vinilica E para exterior en superficie con acabado liso", precio: 50 },
    'PECLSCVINEM2': { nombre: "Servicio de aplicación de pintura vinílica Star Colors Vinilica E para exterior en superficie con acabado liso", precio: 47 },
    'PEARSCVINEM2': { nombre: "Servicio de aplicación de pintura vinílica Star Colors Vinilica E para exterior en superficie con acabado rugoso", precio: 61 },
    'PEBRSCVINEM2': { nombre: "Servicio de aplicación de pintura vinílica Star Colors Vinilica E para exterior en superficie con acabado rugoso", precio: 58 },
    'PECRSCVINEM2': { nombre: "Servicio de aplicación de pintura vinílica Star Colors Vinilica E para exterior en superficie con acabado rugoso", precio: 55 },
    'PEAXSCVINEM2': { nombre: "Servicio de aplicación de pintura vinílica Star Colors Vinilica E para exterior en superficie con acabado extra rugoso", precio: 81 },
    'PEBXSCVINEM2': { nombre: "Servicio de aplicación de pintura vinílica Star Colors Vinilica E para exterior en superficie con acabado extra rugoso", precio: 77 },
    'PECXSCVINEM2': { nombre: "Servicio de aplicación de pintura vinílica Star Colors Vinilica E para exterior en superficie con acabado extra rugoso", precio: 73 },
    'PIALSCVINEM2': { nombre: "Servicio de aplicación de pintura vinílica Star Colors Vinilica E para interior en superficie con acabado liso", precio: 52 },
    'PIBLSCVINEM2': { nombre: "Servicio de aplicación de pintura vinílica Star Colors Vinilica E para interior en superficie con acabado liso", precio: 50 },
    'PICLSCVINEM2': { nombre: "Servicio de aplicación de pintura vinílica Star Colors Vinilica E para interior en superficie con acabado liso", precio: 47 },
    'PIARSCVINEM2': { nombre: "Servicio de aplicación de pintura vinílica Star Colors Vinilica E para interior en superficie con acabado rugoso", precio: 61 },
    'PIBRSCVINEM2': { nombre: "Servicio de aplicación de pintura vinílica Star Colors Vinilica E para interior en superficie con acabado rugoso", precio: 58 },
    'PICRSCVINEM2': { nombre: "Servicio de aplicación de pintura vinílica Star Colors Vinilica E para interior en superficie con acabado rugoso", precio: 55 },
    'PIAXSCVINEM2': { nombre: "Servicio de aplicación de pintura vinílica Star Colors Vinilica E para interior en superficie con acabado extra rugoso", precio: 81 },
    'PIBXSCVINEM2': { nombre: "Servicio de aplicación de pintura vinílica Star Colors Vinilica E para interior en superficie con acabado extra rugoso", precio: 77 },
    'PICXSCVINEM2': { nombre: "Servicio de aplicación de pintura vinílica Star Colors Vinilica E para interior en superficie con acabado extra rugoso", precio: 73 },

    // --- STAR COLORS VIN ES (Original: PREMIUM SATIN) ---
    'PEALSCVINESM2': { nombre: "Servicio de aplicación de pintura vinílica Star Colors Vinilica ES para exterior en superficie con acabado liso", precio: 58 },
    'PEBLSCVINESM2': { nombre: "Servicio de aplicación de pintura vinílica Star Colors Vinilica ES para exterior en superficie con acabado liso", precio: 56 },
    'PECLSCVINESM2': { nombre: "Servicio de aplicación de pintura vinílica Star Colors Vinilica ES para exterior en superficie con acabado liso", precio: 53 },
    'PEARSCVINESM2': { nombre: "Servicio de aplicación de pintura vinílica Star Colors Vinilica ES para exterior en superficie con acabado rugoso", precio: 71 },
    'PEBRSCVINESM2': { nombre: "Servicio de aplicación de pintura vinílica Star Colors Vinilica ES para exterior en superficie con acabado rugoso", precio: 67 },
    'PECRSCVINESM2': { nombre: "Servicio de aplicación de pintura vinílica Star Colors Vinilica ES para exterior en superficie con acabado rugoso", precio: 65 },
    'PEAXSCVINESM2': { nombre: "Servicio de aplicación de pintura vinílica Star Colors Vinilica ES para exterior en superficie con acabado extra rugoso", precio: 95 },
    'PEBXSCVINESM2': { nombre: "Servicio de aplicación de pintura vinílica Star Colors Vinilica ES para exterior en superficie con acabado extra rugoso", precio: 91 },
    'PECXSCVINESM2': { nombre: "Servicio de aplicación de pintura vinílica Star Colors Vinilica ES para exterior en superficie con acabado extra rugoso", precio: 86 },
    'PIALSCVINESM2': { nombre: "Servicio de aplicación de pintura vinílica Star Colors Vinilica ES para interior en superficie con acabado liso", precio: 58 },
    'PIBLSCVINESM2': { nombre: "Servicio de aplicación de pintura vinílica Star Colors Vinilica ES para interior en superficie con acabado liso", precio: 56 },
    'PICLSCVINESM2': { nombre: "Servicio de aplicación de pintura vinílica Star Colors Vinilica ES para interior en superficie con acabado liso", precio: 53 },
    'PIARSCVINESM2': { nombre: "Servicio de aplicación de pintura vinílica Star Colors Vinilica ES para interior en superficie con acabado rugoso", precio: 71 },
    'PIBRSCVINESM2': { nombre: "Servicio de aplicación de pintura vinílica Star Colors Vinilica ES para interior en superficie con acabado rugoso", precio: 67 },
    'PICRSCVINESM2': { nombre: "Servicio de aplicación de pintura vinílica Star Colors Vinilica ES para interior en superficie con acabado rugoso", precio: 65 },
    'PIAXSCVINESM2': { nombre: "Servicio de aplicación de pintura vinílica Star Colors Vinilica ES para interior en superficie con acabado extra rugoso", precio: 95 },
    'PIBXSCVINESM2': { nombre: "Servicio de aplicación de pintura vinílica Star Colors Vinilica ES para interior en superficie con acabado extra rugoso", precio: 91 },
    'PICXSCVINESM2': { nombre: "Servicio de aplicación de pintura vinílica Star Colors Vinilica ES para interior en superficie con acabado extra rugoso", precio: 86 },

    // --- STAR COLORS VIN PRO (Nuevo: PROFESIONAL) ---
    'PEALSCVINPROM2': { nombre: "Servicio de aplicación de pintura vinílica Star Colors Vinilica Pro para exterior en superficie con acabado liso", precio: 62 },
    'PEBLSCVINPROM2': { nombre: "Servicio de aplicación de pintura vinílica Star Colors Vinilica Pro para exterior en superficie con acabado liso", precio: 59 },
    'PECLSCVINPROM2': { nombre: "Servicio de aplicación de pintura vinílica Star Colors Vinilica Pro para exterior en superficie con acabado liso", precio: 56 },
    'PEARSCVINPROM2': { nombre: "Servicio de aplicación de pintura vinílica Star Colors Vinilica Pro para exterior en superficie con acabado rugoso", precio: 77 },
    'PEBRSCVINPROM2': { nombre: "Servicio de aplicación de pintura vinílica Star Colors Vinilica Pro para exterior en superficie con acabado rugoso", precio: 73 },
    'PECRSCVINPROM2': { nombre: "Servicio de aplicación de pintura vinílica Star Colors Vinilica Pro para exterior en superficie con acabado rugoso", precio: 68 },
    'PEAXSCVINPROM2': { nombre: "Servicio de aplicación de pintura vinílica Star Colors Vinilica Pro para exterior en superficie con acabado extra rugoso", precio: 104 },
    'PEBXSCVINPROM2': { nombre: "Servicio de aplicación de pintura vinílica Star Colors Vinilica Pro para exterior en superficie con acabado extra rugoso", precio: 99 },
    'PECXSCVINPROM2': { nombre: "Servicio de aplicación de pintura vinílica Star Colors Vinilica Pro para exterior en superficie con acabado extra rugoso", precio: 94 },
    'PIALSCVINPROM2': { nombre: "Servicio de aplicación de pintura vinílica Star Colors Vinilica Pro para interior en superficie con acabado liso", precio: 62 },
    'PIBLSCVINPROM2': { nombre: "Servicio de aplicación de pintura vinílica Star Colors Vinilica Pro para interior en superficie con acabado liso", precio: 59 },
    'PICLSCVINPROM2': { nombre: "Servicio de aplicación de pintura vinílica Star Colors Vinilica Pro para interior en superficie con acabado liso", precio: 56 },
    'PIARSCVINPROM2': { nombre: "Servicio de aplicación de pintura vinílica Star Colors Vinilica Pro para interior en superficie con acabado rugoso", precio: 77 },
    'PIBRSCVINPROM2': { nombre: "Servicio de aplicación de pintura vinílica Star Colors Vinilica Pro para interior en superficie con acabado rugoso", precio: 73 },
    'PICRSCVINPROM2': { nombre: "Servicio de aplicación de pintura vinílica Star Colors Vinilica Pro para interior en superficie con acabado rugoso", precio: 68 },
    'PIAXSCVINPROM2': { nombre: "Servicio de aplicación de pintura vinílica Star Colors Vinilica Pro para interior en superficie con acabado extra rugoso", precio: 104 },
    'PIBXSCVINPROM2': { nombre: "Servicio de aplicación de pintura vinílica Star Colors Vinilica Pro para interior en superficie con acabado extra rugoso", precio: 99 },
    'PICXSCVINPROM2': { nombre: "Servicio de aplicación de pintura vinílica Star Colors Vinilica Pro para interior en superficie con acabado extra rugoso", precio: 94 },

    // --- COMEX COMXPRO1 (Original: VINLICA COMEX PRO1000) ---
    'PEALCOMXPRO1M2': { nombre: "Servicio de aplicación de pintura vinílica Comex PRO 1000 para exterior en superficie con acabado liso", precio: 61 },
    'PEBLCOMXPRO1M2': { nombre: "Servicio de aplicación de pintura vinílica Comex PRO 1000 para exterior en superficie con acabado liso", precio: 58 },
    'PECLCOMXPRO1M2': { nombre: "Servicio de aplicación de pintura vinílica Comex PRO 1000 para exterior en superficie con acabado liso", precio: 55 },
    'PEARCOMXPRO1M2': { nombre: "Servicio de aplicación de pintura vinílica Comex PRO 1000 para exterior en superficie con acabado rugoso", precio: 75 },
    'PEBRCOMXPRO1M2': { nombre: "Servicio de aplicación de pintura vinílica Comex PRO 1000 para exterior en superficie con acabado rugoso", precio: 71 },
    'PECRCOMXPRO1M2': { nombre: "Servicio de aplicación de pintura vinílica Comex PRO 1000 para exterior en superficie con acabado rugoso", precio: 68 },
    'PEAXCOMXPRO1M2': { nombre: "Servicio de aplicación de pintura vinílica Comex PRO 1000 para exterior en superficie con acabado extra rugoso", precio: 109 },
    'PEBXCOMXPRO1M2': { nombre: "Servicio de aplicación de pintura vinílica Comex PRO 1000 para exterior en superficie con acabado extra rugoso", precio: 99 },
    'PECXCOMXPRO1M2': { nombre: "Servicio de aplicación de pintura vinílica Comex PRO 1000 para exterior en superficie con acabado extra rugoso", precio: 93 },
    'PIALCOMXPRO1M2': { nombre: "Servicio de aplicación de pintura vinílica Comex PRO 1000 para interior en superficie con acabado liso", precio: 61 },
    'PIBLCOMXPRO1M2': { nombre: "Servicio de aplicación de pintura vinílica Comex PRO 1000 para interior en superficie con acabado liso", precio: 58 },
    'PICLCOMXPRO1M2': { nombre: "Servicio de aplicación de pintura vinílica Comex PRO 1000 para interior en superficie con acabado liso", precio: 55 },
    'PIARCOMXPRO1M2': { nombre: "Servicio de aplicación de pintura vinílica Comex PRO 1000 para interior en superficie con acabado rugoso", precio: 75 },
    'PIBRCOMXPRO1M2': { nombre: "Servicio de aplicación de pintura vinílica Comex PRO 1000 para interior en superficie con acabado rugoso", precio: 71 },
    'PICRCOMXPRO1M2': { nombre: "Servicio de aplicación de pintura vinílica Comex PRO 1000 para interior en superficie con acabado rugoso", precio: 68 },
    'PIAXCOMXPRO1M2': { nombre: "Servicio de aplicación de pintura vinílica Comex PRO 1000 para interior en superficie con acabado extra rugoso", precio: 109 },
    'PIBXCOMXPRO1M2': { nombre: "Servicio de aplicación de pintura vinílica Comex PRO 1000 para interior en superficie con acabado extra rugoso", precio: 99 },
    'PICXCOMXPRO1M2': { nombre: "Servicio de aplicación de pintura vinílica Comex PRO 1000 para interior en superficie con acabado extra rugoso", precio: 93 },

    // --- COMEX _ COMXVINIMX (Original: COMEX VINIMEX) ---
    'PEALCOMXVINIMXM2': { nombre: "Servicio de aplicación de pintura vinílica Comex Vinimex para exterior en superficie con acabado liso", precio: 68 },
    'PEBLCOMXVINIMXM2': { nombre: "Servicio de aplicación de pintura vinílica Comex Vinimex para exterior en superficie con acabado liso", precio: 65 },
    'PECLCOMXVINIMXM2': { nombre: "Servicio de aplicación de pintura vinílica Comex Vinimex para exterior en superficie con acabado liso", precio: 61 },
    'PEARCOMXVINIMXM2': { nombre: "Servicio de aplicación de pintura vinílica Comex Vinimex para exterior en superficie con acabado rugoso", precio: 79 },
    'PEBRCOMXVINIMXM2': { nombre: "Servicio de aplicación de pintura vinílica Comex Vinimex para exterior en superficie con acabado rugoso", precio: 81 },
    'PECRCOMXVINIMXM2': { nombre: "Servicio de aplicación de pintura vinílica Comex Vinimex para exterior en superficie con acabado rugoso", precio: 76 },
    'PEAXCOMXVINIMXM2': { nombre: "Servicio de aplicación de pintura vinílica Comex Vinimex para exterior en superficie con acabado extra rugoso", precio: 119 },
    'PEBXCOMXVINIMXM2': { nombre: "Servicio de aplicación de pintura vinílica Comex Vinimex para exterior en superficie con acabado extra rugoso", precio: 105 },
    'PECXCOMXVINIMXM2': { nombre: "Servicio de aplicación de pintura vinílica Comex Vinimex para exterior en superficie con acabado extra rugoso", precio: 105 },
    'PIALCOMXVINIMXM2': { nombre: "Servicio de aplicación de pintura vinílica Comex Vinimex para interior en superficie con acabado liso", precio: 68 },
    'PIBLCOMXVINIMXM2': { nombre: "Servicio de aplicación de pintura vinílica Comex Vinimex para interior en superficie con acabado liso", precio: 65 },
    'PICLCOMXVINIMXM2': { nombre: "Servicio de aplicación de pintura vinílica Comex Vinimex para interior en superficie con acabado liso", precio: 61 },
    'PIARCOMXVINIMXM2': { nombre: "Servicio de aplicación de pintura vinílica Comex Vinimex para interior en superficie con acabado rugoso", precio: 79 },
    'PIBRCOMXVINIMXM2': { nombre: "Servicio de aplicación de pintura vinílica Comex Vinimex para interior en superficie con acabado rugoso", precio: 81 },
    'PICRCOMXVINIMXM2': { nombre: "Servicio de aplicación de pintura vinílica Comex Vinimex para interior en superficie con acabado rugoso", precio: 76 },
    'PIAXCOMXVINIMXM2': { nombre: "Servicio de aplicación de pintura vinílica Comex Vinimex para interior en superficie con acabado extra rugoso", precio: 119 },
    'PIBXCOMXVINIMXM2': { nombre: "Servicio de aplicación de pintura vinílica Comex Vinimex para interior en superficie con acabado extra rugoso", precio: 105 },
    'PICXCOMXVINIMXM2': { nombre: "Servicio de aplicación de pintura vinílica Comex Vinimex para interior en superficie con acabado extra rugoso", precio: 105 },
  },
  ESMALTE: {
    // --- COMXES100 (Original: ESMALTE COMEX 100 - Por m²) ---
    'EEASCOMXES100M2': { nombre: "Servicio de aplicación de pintura de esmalte marca Comex Esmalte 100 para exterior en superficie con acabado sencilla", precio: 93 },
    'EEBSCOMXES100M2': { nombre: "Servicio de aplicación de pintura de esmalte marca Comex Esmalte 100 para exterior en superficie con acabado sencilla", precio: 88 },
    'EECSCOMXES100M2': { nombre: "Servicio de aplicación de pintura de esmalte marca Comex Esmalte 100 para exterior en superficie con acabado sencilla", precio: 83 },
    'EEAMCOMXES100M2': { nombre: "Servicio de aplicación de pintura de esmalte marca Comex Esmalte 100 para exterior en superficie con acabado media", precio: 121 },
    'EEBMCOMXES100M2': { nombre: "Servicio de aplicación de pintura de esmalte marca Comex Esmalte 100 para exterior en superficie con acabado media", precio: 115 },
    'EECMCOMXES100M2': { nombre: "Servicio de aplicación de pintura de esmalte marca Comex Esmalte 100 para exterior en superficie con acabado media", precio: 108 },
    'EEADCOMXES100M2': { nombre: "Servicio de aplicación de pintura de esmalte marca Comex Esmalte 100 para exterior en superficie con acabado difícil", precio: 170 },
    'EEBDCOMXES100M2': { nombre: "Servicio de aplicación de pintura de esmalte marca Comex Esmalte 100 para exterior en superficie con acabado difícil", precio: 164 },
    'EECDCOMXES100M2': { nombre: "Servicio de aplicación de pintura de esmalte marca Comex Esmalte 100 para exterior en superficie con acabado difícil", precio: 155 },
    'EIASCOMXES100M2': { nombre: "Servicio de aplicación de pintura de esmalte marca Comex Esmalte 100 para interior en superficie con acabado sencilla", precio: 89 },
    'EIBSCOMXES100M2': { nombre: "Servicio de aplicación de pintura de esmalte marca Comex Esmalte 100 para interior en superficie con acabado sencilla", precio: 88 },
    'EICSCOMXES100M2': { nombre: "Servicio de aplicación de pintura de esmalte marca Comex Esmalte 100 para interior en superficie con acabado sencilla", precio: 83 },
    'EIAMCOMXES100M2': { nombre: "Servicio de aplicación de pintura de esmalte marca Comex Esmalte 100 para interior en superficie con acabado media", precio: 121 },
    'EIBMCOMXES100M2': { nombre: "Servicio de aplicación de pintura de esmalte marca Comex Esmalte 100 para interior en superficie con acabado media", precio: 115 },
    'EICMCOMXES100M2': { nombre: "Servicio de aplicación de pintura de esmalte marca Comex Esmalte 100 para interior en superficie con acabado media", precio: 108 },
    'EIADCOMXES100M2': { nombre: "Servicio de aplicación de pintura de esmalte marca Comex Esmalte 100 para interior en superficie con acabado difícil", precio: 170 },
    'EIBDCOMXES100M2': { nombre: "Servicio de aplicación de pintura de esmalte marca Comex Esmalte 100 para interior en superficie con acabado difícil", precio: 164 },
    'EICDCOMXES100M2': { nombre: "Servicio de aplicación de pintura de esmalte marca Comex Esmalte 100 para interior en superficie con acabado difícil", precio: 155 },

    // --- COMXES100ML METROS LINEEALES (Original: ESMALTE COMEX 100) ---
    'EEASCOMXES100ML': { nombre: "Servicio de aplicación de pintura de esmalte marca Comex Esmalte 100 para exterior en superficie con acabado sencilla", precio: 93 },
    'EEBSCOMXES100ML': { nombre: "Servicio de aplicación de pintura de esmalte marca Comex Esmalte 100 para exterior en superficie con acabado sencilla", precio: 88 },
    'EECSCOMXES100ML': { nombre: "Servicio de aplicación de pintura de esmalte marca Comex Esmalte 100 para exterior en superficie con acabado sencilla", precio: 83 },
    'EEAMCOMXES100ML': { nombre: "Servicio de aplicación de pintura de esmalte marca Comex Esmalte 100 para exterior en superficie con acabado media", precio: 120 },
    'EEBMCOMXES100ML': { nombre: "Servicio de aplicación de pintura de esmalte marca Comex Esmalte 100 para exterior en superficie con acabado media", precio: 115 },
    'EECMCOMXES100ML': { nombre: "Servicio de aplicación de pintura de esmalte marca Comex Esmalte 100 para exterior en superficie con acabado media", precio: 108 },
    'EEADCOMXES100ML': { nombre: "Servicio de aplicación de pintura de esmalte marca Comex Esmalte 100 para exterior en superficie con acabado difícil", precio: 170 },
    'EEBDCOMXES100ML': { nombre: "Servicio de aplicación de pintura de esmalte marca Comex Esmalte 100 para exterior en superficie con acabado difícil", precio: 164 },
    'EECDCOMXES100ML': { nombre: "Servicio de aplicación de pintura de esmalte marca Comex Esmalte 100 para exterior en superficie con acabado difícil", precio: 155 },
    'EIASCOMXES100ML': { nombre: "Servicio de aplicación de pintura de esmalte marca Comex Esmalte 100 para interior en superficie con acabado sencilla", precio: 93 },
    'EIBSCOMXES100ML': { nombre: "Servicio de aplicación de pintura de esmalte marca Comex Esmalte 100 para interior en superficie con acabado sencilla", precio: 88 },
    'EICSCOMXES100ML': { nombre: "Servicio de aplicación de pintura de esmalte marca Comex Esmalte 100 para interior en superficie con acabado sencilla", precio: 83 },
    'EIAMCOMXES100ML': { nombre: "Servicio de aplicación de pintura de esmalte marca Comex Esmalte 100 para interior en superficie con acabado media", precio: 120 },
    'EIBMCOMXES100ML': { nombre: "Servicio de aplicación de pintura de esmalte marca Comex Esmalte 100 para interior en superficie con acabado media", precio: 115 },
    'EICMCOMXES100ML': { nombre: "Servicio de aplicación de pintura de esmalte marca Comex Esmalte 100 para interior en superficie con acabado media", precio: 108 },
    'EIADCOMXES100ML': { nombre: "Servicio de aplicación de pintura de esmalte marca Comex Esmalte 100 para interior en superficie con acabado difícil", precio: 170 },
    'EIBDCOMXES100ML': { nombre: "Servicio de aplicación de pintura de esmalte marca Comex Esmalte 100 para interior en superficie con acabado difícil", precio: 164 },
    'EICDCOMXES100ML': { nombre: "Servicio de aplicación de pintura de esmalte marca Comex Esmalte 100 para interior en superficie con acabado difícil", precio: 155 },
  },
  EPOXICO: {
    // --- COMXEPOXMULTI (Original: EPÓXICO COMEX MULTIPRO) ---
    'EEASCOMXEPOXMULTIM2': { nombre: "Servicio de aplicación de pintura epóxica marca Comex Epóxico Multipro para exterior en superficie con acabado sencilla", precio: 272 },
    'EEBSCOMXEPOXMULTIM2': { nombre: "Servicio de aplicación de pintura epóxica marca Comex Epóxico Multipro para exterior en superficie con acabado sencilla", precio: 259 },
    'EECSCOMXEPOXMULTIM2': { nombre: "Servicio de aplicación de pintura epóxica marca Comex Epóxico Multipro para exterior en superficie con acabado sencilla", precio: 244 },
    'EEAMCOMXEPOXMULTIM2': { nombre: "Servicio de aplicación de pintura epóxica marca Comex Epóxico Multipro para exterior en superficie con acabado media", precio: 355 },
    'EEBMCOMXEPOXMULTIM2': { nombre: "Servicio de aplicación de pintura epóxica marca Comex Epóxico Multipro para exterior en superficie con acabado media", precio: 338 },
    'EECMCOMXEPOXMULTIM2': { nombre: "Servicio de aplicación de pintura epóxica marca Comex Epóxico Multipro para exterior en superficie con acabado media", precio: 318 },
    'EEADCOMXEPOXMULTIM2': { nombre: "Servicio de aplicación de pintura epóxica marca Comex Epóxico Multipro para exterior en superficie con acabado difícil", precio: 403 },
    'EEBDCOMXEPOXMULTIM2': { nombre: "Servicio de aplicación de pintura epóxica marca Comex Epóxico Multipro para exterior en superficie con acabado difícil", precio: 401 },
    'EECDCOMXEPOXMULTIM2': { nombre: "Servicio de aplicación de pintura epóxica marca Comex Epóxico Multipro para exterior en superficie con acabado difícil", precio: 411 },
    'EIASCOMXEPOXMULTIM2': { nombre: "Servicio de aplicación de pintura epóxica marca Comex Epóxico Multipro para interior en superficie con acabado sencilla", precio: 272 },
    'EIBSCOMXEPOXMULTIM2': { nombre: "Servicio de aplicación de pintura epóxica marca Comex Epóxico Multipro para interior en superficie con acabado sencilla", precio: 259 },
    'EICSCOMXEPOXMULTIM2': { nombre: "Servicio de aplicación de pintura epóxica marca Comex Epóxico Multipro para interior en superficie con acabado sencilla", precio: 244 },
    'EIAMCOMXEPOXMULTIM2': { nombre: "Servicio de aplicación de pintura epóxica marca Comex Epóxico Multipro para interior en superficie con acabado media", precio: 355 },
    'EIBMCOMXEPOXMULTIM2': { nombre: "Servicio de aplicación de pintura epóxica marca Comex Epóxico Multipro para interior en superficie con acabado media", precio: 338 },
    'EICMCOMXEPOXMULTIM2': { nombre: "Servicio de aplicación de pintura epóxica marca Comex Epóxico Multipro para interior en superficie con acabado media", precio: 318 },
    'EIADCOMXEPOXMULTIM2': { nombre: "Servicio de aplicación de pintura epóxica marca Comex Epóxico Multipro para interior en superficie con acabado difícil", precio: 403 },
    'EIBDCOMXEPOXMULTIM2': { nombre: "Servicio de aplicación de pintura epóxica marca Comex Epóxico Multipro para interior en superficie con acabado difícil", precio: 401 },
    'EICDCOMXEPOXMULTIM2': { nombre: "Servicio de aplicación de pintura epóxica marca Comex Epóxico Multipro para interior en superficie con acabado difícil", precio: 411 },
  },
  IMPERMEABILIZANTE: {
    //..
  },
  SELLO: {
    'SIALSCSR1M2': { nombre: "Servicio de aplicación de sellador acrílico Star Colors Acrisello para interior en superficie con acabado liso", precio: 26 },
    'SIBLSCSR1M2': { nombre: "Servicio de aplicación de sellador acrílico Star Colors Acrisello para interior en superficie con acabado liso", precio: 25 },
    'SICLSCSR1M2': { nombre: "Servicio de aplicación de sellador acrílico Star Colors Acrisello para interior en superficie con acabado liso", precio: 23 },
    'SIARSCSR1M2': { nombre: "Servicio de aplicación de sellador acrílico Star Colors Acrisello para interior en superficie con acabado rugoso", precio: 37 },
    'SIBRSCSR1M2': { nombre: "Servicio de aplicación de sellador acrílico Star Colors Acrisello para interior en superficie con acabado rugoso", precio: 35 },
    'SICRSCSR1M2': { nombre: "Servicio de aplicación de sellador acrílico Star Colors Acrisello para interior en superficie con acabado rugoso", precio: 33 },
    'SIAXSCSR1M2': { nombre: "Servicio de aplicación de sellador acrílico Star Colors Acrisello para interior en superficie con acabado extra rugoso", precio: 52 },
    'SIBXSCSR1M2': { nombre: "Servicio de aplicación de sellador acrílico Star Colors Acrisello para interior en superficie con acabado extra rugoso", precio: 49 },
    'SICXSCSR1M2': { nombre: "Servicio de aplicación de sellador acrílico Star Colors Acrisello para interior en superficie con acabado extra rugoso", precio: 47 },
    'SEALSCSR1M2': { nombre: "Servicio de aplicación de sellador acrílico Star Colors Acrisello para interior en superficie con acabado liso", precio: 29 },
    'SEBLSCSR1M2': { nombre: "Servicio de aplicación de sellador acrílico Star Colors Acrisello para interior en superficie con acabado liso", precio: 27 },
    'SECLSCSR1M2': { nombre: "Servicio de aplicación de sellador acrílico Star Colors Acrisello para interior en superficie con acabado liso", precio: 26 },
    'SEARSCSR1M2': { nombre: "Servicio de aplicación de sellador acrílico Star Colors Acrisello para interior en superficie con acabado rugoso", precio: 37 },
    'SEBRSCSR1M2': { nombre: "Servicio de aplicación de sellador acrílico Star Colors Acrisello para interior en superficie con acabado rugoso", precio: 35 },
    'SECRSCSR1M2': { nombre: "Servicio de aplicación de sellador acrílico Star Colors Acrisello para interior en superficie con acabado rugoso", precio: 33 },
    'SEAXSCSR1M2': { nombre: "Servicio de aplicación de sellador acrílico Star Colors Acrisello para interior en superficie con acabado extra rugoso", precio: 52 },
    'SEBXSCSR1M2': { nombre: "Servicio de aplicación de sellador acrílico Star Colors Acrisello para interior en superficie con acabado extra rugoso", precio: 49 },
    'SeCXSCSR1M2': { nombre: "Servicio de aplicación de sellador acrílico Star Colors Acrisello para interior en superficie con acabado extra rugoso", precio: 47 },

  },
  OTROS: {
    'OIASLIJADOM2': { nombre: 'Lijado de superficie - sencillo', precio: 7 },
    'OIBSLIJADOM2': { nombre: 'Lijado de superficie - sencillo', precio: 7 },
    'OICSLIJADOM2': { nombre: 'Lijado de superficie - sencillo', precio: 7 },
    'OIAMLIJADOM2': { nombre: 'Lijado de superficie - medio', precio: 7 },
    'OIBMLIJADOM2': { nombre: 'Lijado de superficie - medio', precio: 7 },
    'OICMLIJADOM2': { nombre: 'Lijado de superficie - medio', precio: 7 },
    'OIADLIJADOM2': { nombre: 'Lijado de superficie - sencillo', precio: 7 },
    'OIBDLIJADOM2': { nombre: 'Lijado de superficie - sencillo', precio: 7 },
    'OICDLIJADOM2': { nombre: 'Lijado de superficie - sencillo', precio: 7 },
    'OEASLIJADOM2': { nombre: 'Lijado de superficie - sencillo', precio: 7 },
    'OEBSLIJADOM2': { nombre: 'Lijado de superficie - sencillo', precio: 7 },
    'OECSLIJADOM2': { nombre: 'Lijado de superficie - sencillo', precio: 7 },
    'OEAMLIJADOM2': { nombre: 'Lijado de superficie - sencillo', precio: 7 },
    'OEBMLIJADOM2': { nombre: 'Lijado de superficie - sencillo', precio: 7 },
    'OECMLIJADOM2': { nombre: 'Lijado de superficie - sencillo', precio: 7 },
    'OEADLIJADOM2': { nombre: 'Lijado de superficie - sencillo', precio: 7 },
    'OEBDLIJADOM2': { nombre: 'Lijado de superficie - sencillo', precio: 7 },
    'OECDLIJADOM2': { nombre: 'Lijado de superficie - sencillo', precio: 7 },
  }
};
